<a href="https://colab.research.google.com/github/eunzzae/Study_NLP/blob/main/231201_%EC%8B%A4%EC%8A%B5_RNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# RNN

In [2]:
import torch
import numpy as np

In [3]:
# Random seed to make results deterministic and reproducible
# 재현성(reproducibility)를 위해 사용되며, 동일한 결과를 얻기위해 시드 설정 필요함.
torch.manual_seed(0)

## RNN layer의 Hyperparameter
* input_size : RNN 레이어로 들어오는 입력 데이터의 feature의 수를 나타낸다. 각 시간 단계에서 입력 벡터의 크기를 의미한다. 예를 들어 단어를 임베딩하는 경우 임베딩 벡터의 크기가 input_size가 된다.
* hidden_size : RNN 레이어의 숨겨진 상태(hidden state)의 크기를 정의한다. RNN이 내부적ㅇ로 유지하는 메모리의 크기를 나타내며, 네트워크의 용량(capacity)과 복잡성(complexity)을 결정한다. hidden_size는 각 시간 단계에서 RNN의 출력 벡터의 크기를 결정한다.

In [4]:
# declare dimension
input_size = 4
hidden_size = 8

## 데이터 셋을 구성
* one-hot vector를 이용해서 글자들을 벡터화 한다.

In [5]:
# singleton example
# shape : (1,1,4)
# input_data_np = np.array([[1,0,0,0]])

# sequential example
# shape : (3,5,4)
h = [1,0,0,0]
e = [0,1,0,0]
l = [0,0,1,0]
o = [0,0,0,1]
input_data_np = np.array([[h,e,l,l,o], [o,l,l,e,h],[l,l,e,e,l]], dtype=np.float32)

In [6]:
input_data_np

array([[[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]],

       [[0., 0., 0., 1.],
        [0., 0., 1., 0.],
        [0., 0., 1., 0.],
        [0., 1., 0., 0.],
        [1., 0., 0., 0.]],

       [[0., 0., 1., 0.],
        [0., 0., 1., 0.],
        [0., 1., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.]]], dtype=float32)

In [7]:
# 데이터의 shape
input_data_np.shape

(3, 5, 4)

In [8]:
# 토치에서 사용하기 위해 변환 필요
input_data = torch.Tensor(input_data_np)

## 모델 구현

In [9]:
# declare RNN
rnn = torch.nn.RNN(input_size=input_size, hidden_size=hidden_size)

## 모델 call
* 모델의 출력결과를 확인

In [10]:
# check output
outputs, _hidden = rnn(input_data)
print(outputs)
print(outputs.size()) # batch, seq, hidden

tensor([[[-0.1615, -0.0684, -0.5179, -0.6718,  0.4243,  0.3967, -0.3416,
          -0.1014],
         [ 0.0294,  0.1610, -0.4207, -0.6110,  0.4818,  0.5262, -0.2557,
           0.0313],
         [-0.4229,  0.0606, -0.5709, -0.5525,  0.0733,  0.2151,  0.0212,
          -0.0170],
         [-0.4229,  0.0606, -0.5709, -0.5525,  0.0733,  0.2151,  0.0212,
          -0.0170],
         [-0.3973,  0.3346, -0.5452, -0.4327,  0.1578,  0.5049, -0.5559,
           0.4022]],

        [[-0.0601,  0.2639, -0.7259, -0.0205,  0.3823,  0.0636, -0.4274,
           0.4885],
         [-0.1513, -0.0610, -0.7351, -0.2362,  0.3506, -0.1910,  0.1731,
           0.0632],
         [ 0.0105,  0.1325, -0.7052, -0.3710,  0.0212, -0.2232,  0.2113,
          -0.2132],
         [ 0.4551,  0.2309, -0.5897, -0.4447,  0.4407,  0.1384, -0.0681,
          -0.1666],
         [ 0.2484, -0.1967, -0.7443, -0.4324,  0.5535, -0.0911, -0.1648,
          -0.1634]],

        [[-0.3254, -0.1276, -0.7445, -0.2957,  0.1946, -0.0568, -0

In [11]:
print(_hidden)
print(_hidden.size()) # 1, seq, hidden

tensor([[[-0.3254, -0.1276, -0.7445, -0.2957,  0.1946, -0.0568, -0.0964,
          -0.0354],
         [-0.2347,  0.0995, -0.6672, -0.3736, -0.0257, -0.0451, -0.0481,
          -0.1722],
         [ 0.2232,  0.2516, -0.5750, -0.5377,  0.3631,  0.3941, -0.2404,
          -0.1992],
         [ 0.0920,  0.0530, -0.6203, -0.4065,  0.6308,  0.3959, -0.2810,
           0.0806],
         [-0.3320,  0.0037, -0.7340, -0.1952,  0.2369, -0.0706, -0.0917,
           0.1069]]], grad_fn=<StackBackward0>)
torch.Size([1, 5, 8])
